[package]
name = "abstract-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
futures = "0.3.25"
pin-project = "1.0.12"
quinn = "0.9.0"
serde = "1.0.147"
tokio = { version = "1.21.2", features = ["full"] }
tokio-serde = { version = "0.8.0", features = ["bincode"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
