name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.65
          override: true
          components: rustfmt, clippy
    - name: fmt 
      run: cargo fmt --all -- --check
    - name: clippy 
      run: cargo --locked clippy --all-targets -- -D warnings
    - name: Build
      run: cargo build --locked --verbose
    - name: Run tests
      run: cargo test --all-features --locked --verbose
